name: Autorelease

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - closed

permissions: {}

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Create new tag
        uses: projectsyn/pr-label-tag-action@796e1eaeafa4de313848e03bd5341d55a08a596d # v1.3.1
        with:
          trigger: |
            Release
